export const blockchains = [
  {
    group: "finance",
    groupLabel: "Finance",
    item: "Arbitrum One",
    slug: "arbitrum-one",
    apiSlug: "arbitrum-one",
    icon: "/blockchains/arbitrumone.svg",
    placeholder: "0x... address",
    coin: "ETH",
    contractAddress: "0x6B435e82bFb27F9308Ad6E67dbecA06828372627",
    chainId: 42161,
    hide: false,
    networkData: {
      chainId: "0xa4b1",
      chainName: "Arbitrum One",
      nativeCurrency: {
        name: "ETH",
        symbol: "ETH",
        decimals: 18,
      },
      rpcUrls: ["https://arb1.arbitrum.io/rpc"],
      blockExplorerUrls: ["https://arbiscan.io"],
    },
  },
  {
    group: "finance",
    groupLabel: "Finance",
    item: "Ethereum",
    slug: "ethereum",
    apiSlug: "ethereum",
    icon: "/blockchains/ethereum.svg",
    placeholder: "0x... or .eth",
    coin: "ETH",
    hide: false,
    contractAddress: "0xbdd3c683af98bbfb3c8c30aac97c9a5119c8cd9f",
    chainId: 1,
    networkData: {
      chainId: "0x1",
      chainName: "Ethereum Mainnet",
      nativeCurrency: {
        name: "ETH",
        symbol: "ETH",
        decimals: 18,
      },
      rpcUrls: ["https://mainnet.infura.io/v3/"],
      blockExplorerUrls: ["https://etherscan.io"],
    },
  },
  {
    group: "finance",
    groupLabel: "Finance",
    item: "Gnosis",
    slug: "gnosis",
    apiSlug: "gnosis",
    icon: "/blockchains/gnosis.svg",
    placeholder: "0x... address",
    coin: "xDAI",
    hide: false,
    contractAddress: "0x4d5f06cC2A7d3a625C95D04Cfaec5AEb5eCfA33D",
    chainId: 100,
    networkData: {
      chainId: "0x64",
      chainName: "Gnosis",
      nativeCurrency: {
        name: "xDAI",
        symbol: "xDAI",
        decimals: 18,
      },
      rpcUrls: ["https://rpc.ankr.com/gnosis"],
      blockExplorerUrls: ["https://gnosisscan.io/"],
    },
  },
  {
    group: "finance",
    groupLabel: "Finance",
    item: "Optimism",
    slug: "Optimism",
    apiSlug: "Optimism",
    icon: "/blockchains/optimism.svg",
    placeholder: "0x... address",
    coin: "ETH",
    hide: false,
    contractAddress: "0xa3e62c1c567d255F25849c8c0b76351e6871Da28",
    chainId: 10,
    networkData: {
      chainId: "0xA",
      chainName: "Optimism",
      nativeCurrency: {
        name: "ETH",
        symbol: "ETH",
        decimals: 18,
      },
      rpcUrls: ["https://mainnet.optimism.io"],
      blockExplorerUrls: ["https://optimistic.etherscan.io"],
    },
  },
  {
    group: "finance",
    groupLabel: "Finance",
    item: "Polygon",
    slug: "polygon",
    apiSlug: "polygon",
    icon: "/blockchains/polygon.svg",
    placeholder: "0x... address",
    coin: "MATIC",
    hide: false,
    contractAddress: "0x286a0a92B65233C39592B97896e93A28682E95A0",
    chainId: 137,
    networkData: {
      chainId: "0x89",
      chainName: "Polygon Mainnet",
      nativeCurrency: {
        name: "MATIC",
        symbol: "MATIC",
        decimals: 18,
      },
      rpcUrls: ["https://polygon-rpc.com"],
      blockExplorerUrls: ["https://polygonscan.com"],
    },
  },
  {
    group: "finance",
    groupLabel: "Finance",
    item: "zkSync Era",
    slug: "zk-sync-era",
    apiSlug: "zk-sync-era",
    icon: "/blockchains/zksync.svg",
    placeholder: "0x... address",
    coin: "ETH",
    hide: false,
    chainId: 324,
    networkData: {
      chainId: "0x144",
      chainName: "zkSync Era Mainnet",
      nativeCurrency: {
        name: "ETH",
        symbol: "ETH",
        decimals: 18,
      },
      rpcUrls: ["https://zksync2-mainnet.zksync.io"],
      blockExplorerUrls: ["https://explorer.zksync.io/"],
    },
  },
  {
    group: "eco",
    groupLabel: "Eco",
    item: "Polygon",
    slug: "polygon_eco",
    apiSlug: "polygon",
    icon: "/blockchains/polygon.svg",
    placeholder: "0x... address",
    coin: "MATIC",
    hide: false,
    contractAddress: "0x20e86a464185dcDF06Cbb58299d430BA3e8358bF",
    ecoTokenAddress: "0x4e78011Ce80ee02d2c3e649Fb657E45898257815",
    chainId: 137,
    networkData: {
      chainId: "0x89",
      chainName: "Polygon Mainnet",
      nativeCurrency: {
        name: "MATIC",
        symbol: "MATIC",
        decimals: 18,
      },
      rpcUrls: ["https://polygon-rpc.com"],
      blockExplorerUrls: ["https://polygonscan.com"],
    },
  },
];
